# Inside your .streamlit/secrets.toml file
OPENAI_API_KEY = "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"
